feat: 로그인 기능 작업 완료
snaps-ariel/new-ground pull request #6
Opened 2024-01-12 08:11 UTC by snaps-odin

## PR Type

- [ ] 버그 수정
- [x] 신규 기능
- [ ] 기타 (기타인 경우 내용 입력 : )

## 작업 내용
- middleware에서 유저 정보 유무에 따라 페이지 처리 (비로그인 상태-> /home 진입 불가, 로그인 상태 -> /login 진입 불가)  
- useSWRMutation을 이용한 로그인 커스텀 훅 생성
- useSWR을 이용한 유저 정보 커스텀 훅 생성
- react-hook-form 라이브러리를 이용한 비제어 컴퍼넌트 생성

## 리뷰어가 중점적으로 봤으면 하는 부분
- 미들웨어 유저 정보 확인 및 페이지 처리 로직에 문제가 없는지
- 관심사 분리에 따른 커스텀 훅 및 기타 구조보다 좋은 패턴이 있을지
- 타입 스크립트 타입 처리 문제 없는지

## (optional) 관련 자료
- react-hook-form / next.js / swr 공식 문서
-

2024-01-12 09:05 UTC, snaps-ariel requested changes
오딘 고민 해주셔서 감사합니다 👍 💯

2024-01-12 09:05 UTC, snaps-ariel commented on src/common/fields/inputField.tsx
> +      {/*)}*/}
이 부분은 왜 주석처리로 하셨는지 궁금합니다 :) !

2024-01-12 09:05 UTC, snaps-ariel commented on src/components/Login/LoginForm.tsx
> +  const { data, trigger, isMutating } = useLogin();
data와 isMutating은 혹시 나중에 사용하실 용도로 남기신 것인지 여쭙습니다! 
trigger은  `trigger:login` 같이 어떤 동작을 하는 함수인지 이름을 지어주면 중복이 되었을 때에도, 코드 상에서 읽을 때에도 더 알아보기 쉬울 것 같습니다 :)

2024-01-12 09:05 UTC, snaps-ariel commented on src/components/Login/LoginForm.tsx
> +import { useRouter } from 'next/navigation';
next 패키지 관련 사항들은 가장 위로 올려주시면 훨씬 보기 깔끔할 것 같아요!

2024-01-12 09:05 UTC, snaps-ariel commented on src/components/Login/index.tsx
> +    </div>
👍

2024-01-12 09:05 UTC, snaps-ariel commented on src/hooks/useUsers.ts
> +}
위에 nextAuth에도 동일한 부분이 있던데 시간 되실때 로그인 전체에 대한 로직 다시 한 번 설명 요청 드립니다 ! 🥇

2024-01-12 09:05 UTC, snaps-ariel commented on src/utils/storage.ts
> +};
storage는 이야기 나눴던 대로 axiosClient로 변경하면 편리할 것 같습니다. 아래 코드에서 token 부분만 세션 스토리지가 아닌 쿠키로 변경해 보면 어떨지요?

```js
import axios, { AxiosRequestConfig, AxiosError } from 'axios';

const axiosClient = axios.create({
  baseURL: process.env.NEXT_PUBLIC_API_URL,
  timeout: 8000,
  headers: {
    'Content-type': 'application/json',
    'X-SNAPS-CHANNEL': 'DA_WEB',
  },
  mode: 'cors',
});

axiosClient.interceptors.request.use(
  (config: AxiosRequestConfig) => {
    if (!config.headers) {
      config.headers = {};
    }

    const token = sessionStorage.getItem('token');

    if (token) {
      config.headers.Authorization = token;
    }

    return config;
  },
  (error: AxiosError) => {
    Promise.reject(error);
  },
);

export default axiosClient;

```

2024-01-12 09:05 UTC, snaps-ariel commented on src/utils/fetcher.ts
> +export const fetcher = (url: string, token: string = '', params = {}) => {
axiosClient를 변경하였다면 해당 코드에 대한 역할을 [인터셉터](https://axios-http.com/kr/docs/interceptors)에서 해주니 fetcher를 다음과 같이 간단하게 변경해주면 좋을 것 같아 의견 드립니다!

```js
export const fetcher = (url: string) => axiosClient.get(url);
```

2024-01-12 09:17 UTC, snaps-ariel commented on src/components/Login/LoginForm.tsx
> +  const { data, trigger, isMutating } = useLogin();
오딘, 이거 추가로 테스트해보니 아래처럼 만들면, data 바로 꺼내 쓸수있더라고요!!
만약 바로 꺼내서 쓴다고 했을 때, 다음과 같이 성공 및 에러 처리 할 수 있을 것 같아 코멘트 달아봅니다! 이후에 보시면 의견 부탁드려용🥇 

```js
export const fetchLogin = async (url: string, { arg }: { arg: IUserInfo }) => {
  const { loginId, password } = arg;
  const { data } = await axiosClient.post('v1/account/user/login', {
    loginId,
    password,
  });

  return data;
};

export const useLogin = () => {
  return useSWRMutation('v1/account/user/login', fetchLogin);
};
```

```js
  const {
    data: loginData,
    error: loginError,
    isMutating,
    trigger: login,
    reset,
  } = useLogin();

  const onSubmit: SubmitHandler<Inputs> = (values) => {
    login({ loginId: values.loginId, password: values.password });
    return;
  };

// 로그인 성공시
  useEffect(() => {
    if (!loginData) return;

    const { token } = loginData;
    Cookies.set('OH_PRINT_ME_GROUND_USER_TOKEN', token, {
      expires: 3,
      path: '/',
    });
    router.push('/home');
  }, [loginData]);

// 로그인 실패시
  useEffect(() => {
    if (!loginError) return;
    console.log(loginError.message);
  }, [loginError]);
```

2024-01-15 00:09 UTC, snaps-odin commented on src/common/fields/inputField.tsx
> +      {/*)}*/}
이 부분은 공통 컴포넌트라, 최대 길이 제한 로직이 생길 시 자연스럽게 추가하려고 했는데... 생각해보니 필요 없는 로직일 것 같아요 ㅎㅎ 삭제 처리 하겠습니다~

2024-01-15 00:15 UTC, snaps-odin commented on src/components/Login/LoginForm.tsx
> +  const { data, trigger, isMutating } = useLogin();
맞네요! 재사용되는 훅에서 같은 변수 명으로 재사용하게 되니 네이밍을 고민해보겠습니다 ㅎㅎ, 그리고 data는 지워야 하는 것이 맞고 isMutating은 remote mutation이 진행 중인 상태를 반환해주기 때문에 버튼의 disabled 값으로 주고 있기 때문에 자연스럽게 mutating인 상태에서 사용자가 버튼이 여러번 누르지 않게 처리해주고 있습니다

2024-01-15 00:53 UTC, snaps-odin commented on src/components/Login/LoginForm.tsx
> +  const { data, trigger, isMutating } = useLogin();
오! 상당히 흥미로운 의견 감사합니다. 반환된 비동기 상태를 이용해서 useEffect로 다음 로직을 처리해주는군요! 가독성도 훨씬 좋아질 것 같습니다

2024-01-15 00:54 UTC, snaps-odin commented on src/components/Login/LoginForm.tsx
> +import { useRouter } from 'next/navigation';
합의된 컨벤션이 없어 개인적으로는 react / next / 외부 라이브러리 --- 내부 컴포넌트 순으로 import 문 정렬하고 있었어요 ㅎㅎ 여기서는 next 패키지가 아래로 왔네요 위로 올리겠습니다 ~!

2024-01-15 00:55 UTC, snaps-odin commented on src/hooks/useUsers.ts
> +}
네 한번 정리해서 설명해드리겠습니다

2024-01-15 00:56 UTC, snaps-odin commented on src/utils/storage.ts
> +};
좋아요! 아래 코멘트까지 포함해서 아리엘 브랜치 한번 푸쉬해주실 수 있을까요??? 폴더 구조랑 전체적인 맥락을 조금 더 파악하고 싶어요 ~~!

2024-01-16 07:34 UTC, snaps-ariel commented on src/components/Login/LoginForm.tsx
> +  const { data, trigger, isMutating } = useLogin();
> 맞네요! 재사용되는 훅에서 같은 변수 명으로 재사용하게 되니 네이밍을 고민해보겠습니다 ㅎㅎ, 그리고 data는 지워야 하는 것이 맞고 isMutating은 remote mutation이 진행 중인 상태를 반환해주기 때문에 버튼의 disabled 값으로 주고 있기 때문에 자연스럽게 mutating인 상태에서 사용자가 버튼이 여러번 누르지 않게 처리해주고 있습니다

오 isMutating 처리에 대한 부분을 제가 놓쳤네요! 설명 감사드립니다!

2024-01-16 07:36 UTC, snaps-ariel commented on src/components/Login/LoginForm.tsx
> +import { useRouter } from 'next/navigation';
제가 한 번 더 오딘께 말씀드리고 함께 정했어야 하는데 오딘 들어오시기 전에 제리랑만 얘기를 했었네요 ㅠㅠ!!! [여기](https://www.notion.so/snaps-corp/convention-guide-29ca9ab90aee474bb35d09b7835b3e4d?pvs=4) 참조 부탁드리고, 저도 패키지들은 오딘께서 말씀하신 것처럼 react / next / 외부 라이브러리 순으로 정렬하겠습니다! :)

2024-01-17 08:14 UTC, snaps-ariel commented on src/hooks/useUsers.ts
> +}
오딘 설명 감사해요~~!!!! 덕분에 알게 되었어요!

2024-01-17 08:15 UTC, snaps-ariel commented on src/utils/storage.ts
> +};
@snaps-odin [이 pr](https://github.com/snaps-ariel/new-ground/pull/9) 에 푸시해두었어요! 👍

2024-01-17 08:16 UTC, snaps-ariel commented on src/utils/fetcher.ts
> +export const fetcher = (url: string, token: string = '', params = {}) => {
요 부분도 위에서 남긴 pr 링크에 같이 있습니당 :) 작업 기다려주셔서 감사해요!

2024-01-22 00:49 UTC, merged